server:
  port: ${PORT:8761}
#
spring:
  application:
    name: discovery-server
#
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck.enabled: false
    service-url.defaultZone: http://localhost:${server.port}/eureka/
  instance:
    prefer-ip-address: true
#
